### ISSUE TITLE
Integrate SystemAlerter with current factory classes.

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#106]
The factory class implementations for alerting where done after the `SystemAlerter` was implemented, therefore they were not integrated.

In this ticket we should do the following:

- [x] At the moment 1 system alerter per chain is started. We need 1 `SystemAlerter` for everything, similarly to the `CosmosNodeAlerter`. This must be reflected in both the manager and the alerter.
- [x] Implement the `SystemAlerter` similarly to other alerters by integrating it with the alerting factory.
- [x] We must make sure that the `SystemAlertersManager` has a similar implementation as the other managers. 
- [x] We need to also check that all config queues in the `SystemAlerter` and `SystemAlertersManager` have been declared inside the `run_alerter`.
- [x] We must check that the Telegram and Slack Command Handlers are updated.
- [x] Update the routing keys from the `SystemDataTransformer`.
- [x] Update alerter tests, as required.
- [x] Fix `alerts-overview` endpoint call in `systems-overview` page in UI.
- [x] Release hotfix.

**Comment by crsfalzon** [comment]
hotfix with #165
