### ISSUE TITLE
System Test Cosmos Alerting

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#108]
In this task one PANIC team member should spend some time testing all Cosmos alerts. This should be done on a release candidate.

**Comment by Cherrett** [comment]
It was noticed that `validator active in session` based alerts such as `Validator 123 is not in the active set of validators` are also being raised for nodes which are not validators (`is_validator=false`). This will also be checked for other alerts which should only be raised if node is set as a validator (`is_validator=true`). From the logic POV, it is correct, and the endpoint for checking the validator status is not called if the node is not a validator. Only the alerting logic should be changed. - FIXED

**Comment by Cherrett** [comment]
https://github.com/SimplyVC/panic/issues/124

**Comment by Cherrett** [comment]
https://github.com/SimplyVC/panic/issues/126
