### ISSUE TITLE
Post UAT UI iteration 1 - Investigation - Whitelist PANIC Host IP

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#121]
During the investigation of the issue where the UI service wasn't being able to fetch data from API service we found out that CORS config was missing (to allow calls to the API from a different origin). The solution was to whitelist the VM's IP (VM which is running PANIC UAT) in the API service. Currently it's hard-coded and works only for the UAT (User Acceptance Tests).

We need to find a solution that whitelists the IP from the VM that PANIC is running on. Ideally this logic would find out the host IP in build time and then feed that info to the API service somehow, so it can be whitelisted. If this is not achievable, then I think that we should have a meeting to discuss the solutions.

**Comment by dillu24** [comment]
[IP-1647270241492.log](https://github.com/SimplyVC/panic/files/8246261/172.16.152.17-1647270241492.log)

The stencil.js config and the cors were changed to the VM IP for UAT.
