### ISSUE TITLE
Post UAT UI Iteration 1 - Investigate Redis connection crash in API

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#130]
Yesterday at 5.30pm Timo reported that PANIC UI was inaccessible. After looking at the logs of the API it was noticed that the Redis connection was broken:

```
Error: Redis connection in broken state: retry aborted.
api_1             |     at RedisClient.connection_gone (/opt/panic/api/node_modules/redis/index.js:569:30)
api_1             |     at Socket.<anonymous> (/opt/panic/api/node_modules/redis/index.js:231:14)
api_1             |     at Object.onceWrapper (events.js:519:28)
api_1             |     at Socket.emit (events.js:412:35)
api_1             |     at endReadableNT (internal/streams/readable.js:1334:12)
api_1             |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
api_1             |   code: 'CONNECTION_BROKEN'
api_1             | }
panic_api_1 exited with code 137
```

This morning it was also noted that all panic components (including the alerter) were not running i.e. docker services were not running. Therefore, the above could have occurred due to a vm restart or a human mistake. At the moment PANIC is running on the VM to try and check whether the above occurs again.

Nonetheless, the task of this ticket is to check that whenever the Redis/Mongo connection is broken (by disconnecting from vpn or similar) the API does not crash, and hence appropriate Error handling is implemented.

**Comment by dillu24** [comment]
Another important thing to note is that all services crashed with code 137. Therefore we must investigate why the containers crashed, as there may be a memory leak. I suggest we perform a memory analysis here.

**Comment by Cherrett** [comment]
The following must be checked:

- Whenever we kill redis, mongo and rabbit for a long time .. all services don't crash and re-connect when they are back up
- Memory analysis to see where we are wasting memory the most

**Comment by dillu24** [comment]
Tasks performed in this ticket:

1. Disconnect RabbitMQ for 1 hour and check that all docker services and panic alerter components re-connect after it is up.

    **Outcome**: The configs manager failed in this case and ticket https://github.com/SimplyVC/panic/issues/136 was opened.

2. Disconnect Redis for 1 hour and check that all docker services and panic alerter components re-connect after it is up.

   **Outcome**: The API attempts to re-connect as expected, however, it tries to send the data to the front-end end even after the data is sent. This issue was solved.

```
AbortError: Redis connection in broken state: retry aborted.
api_1             |     at RedisClient.flush_and_error (/opt/panic/api/node_modules/redis/index.js:298:23)
api_1             |     at RedisClient.connection_gone (/opt/panic/api/node_modules/redis/index.js:563:18)
api_1             |     at RedisClient.on_error (/opt/panic/api/node_modules/redis/index.js:346:10)
api_1             |     at Socket.<anonymous> (/opt/panic/api/node_modules/redis/index.js:223:14)
api_1             |     at Socket.emit (events.js:400:28)
api_1             |     at emitErrorNT (internal/streams/destroy.js:106:8)
api_1             |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
api_1             |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
api_1             |   code: 'CONNECTION_BROKEN',
api_1             |   command: 'HGETALL',
api_1             |   args: [
api_1             |     'panic_alerter:hash_p1_chain_name_7f22f0f8-f3c6-4f6c-a5fc-2e1f49df4064'
api_1             |   ],
api_1             |   origin: Error: connect EHOSTUNREACH 172.18.0.5:6379
api_1             |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
api_1             |     errno: -113,
api_1             |     code: 'EHOSTUNREACH',
api_1             |     syscall: 'connect',
api_1             |     address: '172.18.0.5',
api_1             |     port: 6379
api_1             |   }
api_1             | }
api_1             | AbortError: Redis connection in broken state: retry aborted.
api_1             |     at RedisClient.flush_and_error (/opt/panic/api/node_modules/redis/index.js:298:23)
api_1             |     at RedisClient.connection_gone (/opt/panic/api/node_modules/redis/index.js:563:18)
api_1             |     at RedisClient.on_error (/opt/panic/api/node_modules/redis/index.js:346:10)
api_1             |     at Socket.<anonymous> (/opt/panic/api/node_modules/redis/index.js:223:14)
api_1             |     at Socket.emit (events.js:400:28)
api_1             |     at emitErrorNT (internal/streams/destroy.js:106:8)
api_1             |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
api_1             |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
api_1             |   code: 'CONNECTION_BROKEN',
api_1             |   command: 'HGETALL',
api_1             |   args: [
api_1             |     'panic_alerter:hash_p1_chain_name_8d2ea772-1675-43ce-b864-d591bec1d100'
api_1             |   ],
api_1             |   origin: Error: connect EHOSTUNREACH 172.18.0.5:6379
api_1             |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
api_1             |     errno: -113,
api_1             |     code: 'EHOSTUNREACH',
api_1             |     syscall: 'connect',
api_1             |     address: '172.18.0.5',
api_1             |     port: 6379
api_1             |   }
api_1             | }
api_1             | _http_outgoing.js:561
api_1             |     throw new ERR_HTTP_HEADERS_SENT('set');
api_1             |     ^
api_1             | 
api_1             | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
api_1             |     at new NodeError (internal/errors.js:322:7)
api_1             |     at ServerResponse.setHeader (_http_outgoing.js:561:11)
api_1             |     at ServerResponse.header (/opt/panic/api/node_modules/express/lib/response.js:771:10)
api_1             |     at ServerResponse.send (/opt/panic/api/node_modules/express/lib/response.js:170:12)
api_1             |     at ServerResponse.json (/opt/panic/api/node_modules/express/lib/response.js:267:15)
api_1             |     at ServerResponse.send (/opt/panic/api/node_modules/express/lib/response.js:158:21)
![Figure_1](https://user-images.githubusercontent.com/23262259/159563231-a8bd94d4-d037-4d9f-a619-ff1cf02b29e0.png)

api_1             |     at /opt/panic/api/src/server.js:460:51
api_1             |     at Command.command_obj.callback (/opt/panic/api/node_modules/redis/lib/multi.js:31:17)
api_1             |     at RedisClient.flush_and_error (/opt/panic/api/node_modules/redis/index.js:310:29)
api_1             |     at RedisClient.connection_gone (/opt/panic/api/node_modules/redis/index.js:563:18) {
api_1             |   code: 'ERR_HTTP_HEADERS_SENT'
api_1             | }
```

3. Disconnect Mongo for 1 hour and check that all docker services and panic alerter components re-connect after it is up.

    **Outcome**: All services and alerter components re-connect with Mongo

4. Perform memory analysis.

I performed memory analysis on the alerter code from the release candidate branch using mprof by installing mprof as a dependency and putting the following command in the Alerter_Dockerfile: `CMD /wait && pipenv run mprof run python run_alerter.py`. Then, the profiler output file was copied to the host using `sudo docker cp 176fbcaa1227:opt/panic/alerter/mprofile_20220322134500.dat ~/Documents/panic_gitlab/panic/alerter`, and the usage was plotted using `mprof plot`.

source: https://pypi.org/project/memory-profiler/

**Outcome**: PANIC was left running for 5.5 hours, and as shown in the plot below no memory leaks were spotted as otherwise spikes in memory would be visible:

![Figure_1](https://user-images.githubusercontent.com/23262259/159563231-a8bd94d4-d037-4d9f-a619-ff1cf02b29e0.png)

5. Run PANIC over the weekend to spot memory leaks. 

    **Outcome**: Memory usage was kept constant throughout the weekend and no docker service or alerter component crashed.
