### ISSUE TITLE
Post UAT UI Iteration 1 - ErrorContractsNotRetrieved not raised by Chainlink Contracts Monitor when all nodes are down

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#133]
During UAT,  Timo added a chainlink node for node monitoring and contracts monitoring. After switching off the VPN, a node downtime alert was raised as expected, however, an ErrorContractsNotRetrieved alert was not raised.

We need to investigate why this happened and if there is a bug we need to solve it.

**Comment by Cherrett** [comment]
This is the expected behaviour since `ErrorNoSyncedDataSources` alert is raised in this case. Moreover, `ErrorContractsNotRetrieved` is only raised when contracts could not be retrieved from weiwatchers. @crsfalzon

**Comment by dillu24** [comment]
@Cherrett Opened this again. The issue is now the resolved alert.
