### ISSUE TITLE
Improper connection handling in ConfigsManager

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#136]
If RabbitMQ is taken down after PANIC is running, the ConfigsManager enters in a loop of starting and stopping. We need to check that proper connection handling is being done inside the ConfigsManager.

**Comment by Cherrett** [comment]
![image](https://user-images.githubusercontent.com/49488952/159246087-5558c0f8-46a3-4188-93b9-febd5ba59d96.png)

**Comment by Cherrett** [comment]
![image](https://user-images.githubusercontent.com/49488952/159256865-cf1b6b95-f8b2-47ba-8080-e505d1f705e8.png)
