### ISSUE TITLE
Substrate Alerting - Implement Alerting Logic (Network)

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#144]
### Technical stories

We want to form logic around the transformed data sent by the substrate network data transformer. This logic will entail which alerts to be raised/solved.

### Description

A `SubstrateNetworkAlerter` publisher-subscriber component should be developed, and the following tasks should be done:

1. Go through the [metrics research]([Substrate_Metrics_Research.ods](https://github.com/SimplyVC/panic/files/8601173/Substrate_Metrics_Research.ods)) and the `SubstrateNetworkDataTransformer` implementation to understand what are the metrics being retrieved and the alerting requirements.
2. Perform some data retrieval by running PANIC and logging the data to understand how the raw data looks like.
3. Connect the `SubstrateNetworkAlerter` with RabbitMQ to start receiving Substrate network transformed data.
4. Perform any logic for raising/solving alerts. This must include new proposals, new referendums, concluded referendums, (no) synced substrate data sources found, and substrate network data could not be obtained/ can be obtained.
5. Send the alerts data for alerting and storing to the alert exchange.
6. Create the `SubstrateAlertersManager` while being aware of the new `SubstrateNetworkAlerter`. This is needed so that the manager can start and manage the re-starting of the newly developed alerter.
7. The component can process heartbeats

Some final checks before putting an MR:

1. Make sure to declare newly created config queues in the `run_alerter.py` file. This is needed just in case the configs manager starts sending queues before the component queues were declared (if any).
2. Check that the Telegram Commands Handler and the Slack Commands Handler are aware of the new components' heartbeats (if any).

### Blocked by

#110 (Substrate Network data transformer)

### For ticket closure _(acceptance criteria)_

This is a set of rules which the update/feature must satisfy for the ticket to be closed.

**Scenario**: The `SubstrateNetworkAlerter` is started
**Given**:  PANIC started
**When**: Checking the log files inside the `alerter/logs/alerters` and the docker-compose console
**Then**: You can see correct startup

**Scenario**: The `SubstrateNetworkAlerter` has no error logs (apart from the data sending part due to no consumer)
**Given**:  PANIC is running
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see no error logs

**Scenario**: The `SubstrateNetworkAlerter` is receiving transformed data from the `SubstrateNetworkDataTransformer`
**Given**:  PANIC is running in Debug mode (by putting `LOGGING_LEVEL=INFO` inside the `.env` file and restarting panic)
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see the correct data being received.

**Scenario**: The `SubstrateNetworkAlerter` is raising alerts correctly
**Given**:  PANIC is running in Debug mode (by putting `LOGGING_LEVEL=INFO` inside the `.env` file and restarting panic)
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see the correct alerts.

**Scenario**: The `Telegram Commands Handler` and `Slack Commands Handler` do not show any issues on `/status` and `/panicstatus` commands respectively.
**Given**:  PANIC is running with a Slack Commands Handler and Telegram Commands Handler
**When**: Typing `/status` and `/panicstatus`
**Then**: You can see that PANIC is running smoothly

**Comment by Cherrett** [comment]
We must make sure to include a unique redis key for each new proposal. new referendum, and finished referendum. This way, we will assure that no alerts of these types are overridden. These will be set with an expiry value and will be removed by a future component (#204).
