### ISSUE TITLE
Prepare Substrate P1s release candidate for UAT

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#146]
### Technical Story

When the Substrate alerting development is done we need to perform some tasks before submitting our new functionality to UAT for the staking team

### Requirements

- [x] Create a branch from `feature/substrate-p1-alerting` and name it `release/substrate-p1-alerting`
- [x] Read and update the existing `README.md` so that it includes mentioning Substrate P1
- [x] Read and update the UI documentation to confirm that it is up to date
- [x] Include Substrate P1 alerting and monitoring in the `design_and_features.md` alerting section and architecture design image. It is best to read the entire docs to make sure that it still makes sense.
- [x] Make sure we are using latest version of Substrate API
- [x] Update docker containers versioning and any `package.json` (don't forget to run `npm install` to also update the `package_lock.json`)
- [x] Make sure all tests pass
- [x] Make sure installer journey is correct for Substrate
- [x] Come up with an upgrade strategy for previously added Substrate nodes/alerts
- [x] Prepare a list of test cases together with the corresponding data sources (dummy or where possible live data)
- [x] Run PANIC and make sure everything is working as intended
- [x] Deploy release candidate on the dev vm

Deploy:
When the above is ready we should ask the staking team for a vm so that we run a release candidate for them to review.

### Blocked by

This ticket should only be tackled if all previous substrate tickets have been closed.

**Comment by Cherrett** [comment]
We must make sure to update the Substrate API to the latest version before carrying out any testing

**Comment by Cherrett** [comment]
We must include an upgrade strategy for previously added substrate nodes/alerts.
