### ISSUE TITLE
Substrate Alerting - Implement Alerting Logic (Node)

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#150]
### Technical stories

We want to form logic around the transformed data sent by the substrate node data transformer. This logic will entail which alerts to be raised/solved.

### Description

A `SubstrateNodeAlerter` publisher-subscriber component should be developed, and the following tasks should be done:

1. Go through the [metrics research]([Substrate_Metrics_Research.ods](https://github.com/SimplyVC/panic/files/8601173/Substrate_Metrics_Research.ods)) and the `SubstrateNodeDataTransformer` implementation to understand what are the metrics being retrieved and the alerting requirements.
2. Perform some data retrieval by running PANIC and logging the data to understand how the raw data looks like.
3. Connect the `SubstrateNodeAlerter` with RabbitMQ to start receiving Substrate node transformed data.
4. Perform any logic for raising/solving alerts according to the research conducted and the data obtained from the data transformer.
5. Send the alerts data for alerting and storing to the alert exchange.
6. Add logic in the `SubstrateAlertersManager` so that it is aware of the new `SubstrateNodeAlerter`. This is needed so that the manager can start and manage the re-starting of the newly developed alerter.
7. The component can process heartbeats

Some final checks before putting an MR:

1. Make sure to declare newly created config queues in the `run_alerter.py` file. This is needed just in case the configs manager starts sending queues before the component queues were declared (if any).
2. Check that the Telegram Commands Handler and the Slack Commands Handler are aware of the new components' heartbeats (if any).

### Blocked by

#149 (Substrate Node Data Transformer)
#212 

### Acceptance criteria

**Scenario**: The `SubstrateNodeAlerter` is started
**Given**:  PANIC started
**When**: Checking the log files inside the `alerter/logs/alerters` and the docker-compose console
**Then**: You can see correct startup

**Scenario**: The `SubstrateNodeAlerter` has no error logs (apart from the data sending part due to no consumer)
**Given**:  PANIC is running
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see no error logs

**Scenario**: The `SubstrateNodeAlerter` is receiving transformed data from the `SubstrateNodeDataTransformer`
**Given**:  PANIC is running in Debug mode (by putting `LOGGING_LEVEL=INFO` inside the `.env` file and restarting panic)
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see the correct data being received.

**Scenario**: The `SubstrateNodeAlerter` is raising alerts correctly
**Given**:  PANIC is running in Debug mode (by putting `LOGGING_LEVEL=INFO` inside the `.env` file and restarting panic)
**When**: Checking the log files inside the `alerter/logs/alerters`
**Then**: You can see the correct alerts.

**Scenario**: The `Telegram Commands Handler` and `Slack Commands Handler` do not show any issues on `/status` and `/panicstatus` commands respectively.
**Given**:  PANIC is running with a Slack Commands Handler and Telegram Commands Handler
**When**: Typing `/status` and `/panicstatus`
**Then**: You can see that PANIC is running smoothly

**Comment by Cherrett** [comment]
Once #212 is merged, we should to the following:

Any Substrate Node alerts which make use of balance values should be updated accordingly while also adding functionality for including the token symbol as a postfix. This includes bonded balance change and slashing alerts. The Substrate Node Alerter should be updated to use the new data sent by the Substrate Node Data Transformer while sending the correct data to the modified alerts.
