### ISSUE TITLE
Substrate Alerting: Update Alert Store

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#152]
### Technical Story

The PANIC Alerter must be able to store the alerts (excluding those with INTERNAL severity) raised by the `SubstrateNetworkAlerter` and the `SubstrateNodeAlerter` in Mongo, and the variouis metrics state in Redis. In addition to this, the Alert Store should be able to reset the various substrate metrics whenever an internal alert is received.

### Requirements

- [x] `_LIST_OF_ALERTERS` should include the `SubstrateNetworkAlerter` and the `SubstrateNodeAlerter`
- [x] Create the required alerting keys and functions for both the `SubstrateNetworkAlerter` and the `SubstrateNodeAlerter` inside the `store_keys.py`
- [x] Add metrics that cannot be resolved as `EXPIRE_METRIC`
- [x] Proposals/referendum alert metrics' state needs to be saved differently because we require to index the keys by the referendum/proposal index.
- [x] PayoutNotClaimed/PayoutClaimed alert metrics' state needs to be saved differently because we require to index the keys by the era index.
- [x] Slashing and Offline alert metrics' state needs to be saved differently because we require to index the keys by the block index.

### Blocked by

#144  #150   

### Acceptance criteria

**Scenario**: Alerts are stored in Mongo whenever they are raised
**Given**: Any alert is raised
**When**: ssh'ing into the mongo docker container
**Then**: I can see the stored alert in mongo

**Scenario**: The corresponding alert metric state is stored in Redis whenever an alert is raised
**Given**: Any alert is raised
**When**: ssh'ing into the redis docker container
**Then**: I can see the stored metric state in redis

**Scenario**: The metric state is removed from redis on an INTERNAL ALERT
**Given**: PANIC is restarted
**When**: ssh'ing into the redis docker container
**Then**: I can see that the metric states have been removed

**Comment by Cherrett** [comment]
We must make sure to include a unique redis key for each new proposal and new/finished referendum. This way, we will assure that no alerts of these types are overridden. These will be set with an expiry value and will be removed by a future component (https://github.com/SimplyVC/panic/issues/204).

**Comment by dillu24** [comment]
Note that for referendums we should use `referendum_concluded` as a way of resolving a `new_referendum` alert, just in case short referendums are created in the future. This should also be done for Cosmos.

**Comment by Cherrett** [comment]
The above comments also apply for payout not claimed/claimed alerts, slashing alerts, offline alerts, and did not send heartbeat and did not author blocks yet alert.
