### ISSUE TITLE
Substrate Alerting: Update API/UI

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#153]
### Technical Story

As the API I want to be able to return substrate alerts as required and as the UI I want to be able to get substrate alerts. 

### Description

We must update the API to cater for new substrate node/network alert keys from redis. We must make sure that we also cater for unique keys (for payout not claimed/claimed alerts and proposals/referendums alerts).
We must also make any additional changes to the UI so that it gets all of the required alerts as necessary (might not be needed)

### Requirements

- Add new alert keys of substrate node/substrate network to the API
- Add the required logic in the API for fetching the above alert keys if found
- Modify the UI to cater for new alerts (if necessary)
- Make sure that different type of alerts are being shown in the UI.

### Blocked by

#152 

### Acceptance criteria

**Scenario**: The `API` is started
**Given**:  Built and started API via docker
**When**: Checking the log from within the docker-compose console
**Then**: You can see correct startup

**Scenario**: API returning correct substrate alerts
**Given**:  The `API` is running
**When**: Sending API requests to the API
**Then**: You can see any active substrate alerts in the response

**Scenario**: The `API` has no error logs
**Given**:  The `API` is running and requests were sent
**When**: Checking the log from within the docker-compose console
**Then**: You can see no error logs

**Scenario**: The `UI` is showing substrate alerts
**Given**:  The `API` and `UI` are running
**When**: Substrate alerts are raised within PANIC
**Then**: You can see any active substrate alerts in the UI

**Comment by Cherrett** [comment]
We must make sure to cater for unique keys for proposals/referendums. This will have similar logic to what we currently have for fetching chainlink contracts alerts within the API.

**Comment by Cherrett** [comment]
The above comment also applies for payout not claimed/claimed alerts

**Comment by dillu24** [comment]
Starting this review

**Comment by dillu24** [comment]
Reviewed
