### ISSUE TITLE
PANIC Installer Journey - Amendments and Improvements

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#155]
This issue will be used to keep track of any PANIC UI amendments required for the second iteration.

**Comment by Cherrett** [comment]
@zimaah:

PANIC board
Installer - Sub-chain: required attribute must be set on base-chain select...

UI Kit board
SVCSelect: add support for required attribute

**Comment by Cherrett** [comment]
PANIC board
Update chainlink node to take multiple prometheus URLs.

UI Kit board
Create input component which supports multiple inputs (UILIB-108)

**Comment by Cherrett** [comment]
PANIC board
Remove `@ts-ignore` from InstallerAPI where `svc-input` is used within `FormInterface`.

UI Kit board
Add `svc-input` as a valid component tag name in `FormInterface`.

**Comment by itsciccio** [comment]
PANIC board
Channels setup - modify necessary form components to accept multiple inputs. Also add functionality that these inputs are saved correctly. Also add functionality that loads the multiple inputs into a form (when editing) + saves accordingly.

**Comment by Cherrett** [comment]
PANIC board
Remove logic of converting `true` and empty strings into boolean values within forms.

UI Kit board
Update `svc-toggle` and `svc-checkbox` to have boolean values instead of `string | number` so we have better logic in forms.

**Comment by itsciccio** [comment]
PANIC board
channels setup (and maybe all other form inputs) - if user added data, and they click away to close the modal or leave the page, show a modal to confirm that if they navigate away, all their unsaved data will be lost (similar to the installer)

**Comment by Cherrett** [comment]
PANIC board
Data tables with node/system data with `overflow: auto` CSS does not show border/shadow.

**Comment by Cherrett** [comment]
PANIC board
Update `svc-input` instances which have the `disabled` prop to `readonly` which results in a neater solution.

UI Kit board
Update `svc-input` to accept the `readonly` prop which will be passed to the `ion-input` `readonly` prop, as can be seen [here](https://ionicframework.com/docs/api/input#readonly).

**Comment by Cherrett** [comment]
UI Kit board
Error in `svc-toast` after being dismissed.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/49488952/163359301-72255fae-8fa9-40c5-b33b-866220cfd3c5.png">

**Comment by Cherrett** [comment]
PANIC board
Update validation for unique channels/sources names.

**Comment by Cherrett** [comment]
UI Kit board
Update `svc-data-table` to give original index, not index of when elements are sorted.

Proposal: enforce an `id` prop in the data displayed in the `rows` prop, and then forward that `id` value along with the edit/delete event.

**Comment by Cherrett** [comment]
PANIC board
I suggest that we should wrap `panic-dashboard-overview` and `panic-alerts-overview` within a parent component which passes data to them. This should be done since we are calling the `monitorablesInfo` endpoint twice per 5 seconds, which is not ideal.

**Comment by crsfalzon** [comment]
Use workaround to enforce the completion of inputs by checking that each input is done. (Blockchain setup - installer)

**Comment by itsciccio** [comment]
UI Kit board

Include the `disabled` attribute for `svc-select`.

When this is done, fix installer channels edit form to disable the `svc-select` via an attribute instead of using the `pointer-events: none` workaround.

**Comment by itsciccio** [comment]
We should update all tests in PANIC UI covering different test cases etc

**Comment by itsciccio** [comment]
PANIC Board

In the case other `FormFieldInterface` components (apart from `svc-checkbox` and `svc-input`) are required to be loaded in the edit channel modal form, these need to be handled as so far only the mentioned 2 are supported. This improvement may be necessary once we implement the `SVCMultipleInput` component in the next UI Kit release.

**Comment by zimaah** [comment]
> PANIC board I suggest that we should wrap `panic-dashboard-overview` and `panic-alerts-overview` within a parent component which passes data to them. This should be done since we are calling the `monitorablesInfo` endpoint twice per 5 seconds, which is not ideal.

@Cherrett I think that it falls under a diff domain, let's try to focus on installer fixes here ;)
It's definitely important, so just move this note somewhere else :+1:

**Comment by itsciccio** [comment]
PANIC Board

Error handling across installer journey components

**Comment by itsciccio** [comment]
UI Kit

Wrap `ion-progress-bar` into a UIKit component (ex. `svc-progress-bar`)

**Comment by itsciccio** [comment]
PANIC Board

If no channels are added, we need to inform the user that they will not be able to be alerted (the same is done on the old installer)

**Comment by itsciccio** [comment]
PANIC Board

Add a linter to enforce a code style standard

**Comment by Cherrett** [comment]
> PANIC Board
> 
> Add a linter to enforce a code style standard

FYI: There was a ticket for this on JIRA I believe

**Comment by itsciccio** [comment]
PANIC Board

![image](https://user-images.githubusercontent.com/50298612/167798519-0587616a-248f-413e-9ccc-724681bab97f.png)
![image](https://user-images.githubusercontent.com/50298612/167798547-18509b3d-c389-4543-9dc7-36e6681b3486.png)

The above containers have identical css styling. The issue here is that the width scales depending on the contents of the container. In the images, for example, one has a greater length of text causing the container to widen accordingly. We should enforce either a constant width or at least a maximum/minimum width it can scale to.

**Comment by itsciccio** [comment]
PANIC Board (+ possibly API side when it comes to entities)

Set the correct types of variables throughout the different installer journey components, based on @simplyrider 's entities.

**Comment by itsciccio** [comment]
PANIC Board

Node test buttons: Add functionality that automatically disables the 'clickability' of the `TEST` button if no text has been inputted

**Comment by itsciccio** [comment]
PANIC Board

Amend types across all installer components to comply with the data format used on the API/modals side.

**Comment by itsciccio** [comment]
PANIC Board

`panic-installer-alerts` E2E test - an issue with this e2e tests causes the snapshot to render without content.

**Comment by itsciccio** [comment]
PANIC Board

`panic-installer-alerts` baseChain prop - in its current state, the base chain value is hardcoded to 'cosmos'. In order to amend this, we have to pass the appropriate base chain string value from `panic-root` down to this component in order to render the required alerts.

**Comment by itsciccio** [comment]
PANIC Board

Rename usages of `svc-filter` to `svc-event-emitter` to complu with the new UI Kit 1.3.0 release. Also assert that no other components are broken with the new release.

**Comment by Cherrett** [comment]
UI Kit

Investigate how we can dynamically modify `FormFieldInterface` to allow for custom components. This is needed to avoid the use of `@ts-ignore`.

An example of this can be seen here: 

![image](https://user-images.githubusercontent.com/49488952/174082576-226ea694-736d-44d7-a30a-8980b7a80c97.png)

**Comment by itsciccio** [comment]
PANIC Board

Investigate e2e tests as some are not up-to-date anymore due to changes/new components

**Comment by itsciccio** [comment]
PANIC Board

Channels form bug: when entering new channel data, for example the configuration name for PagerDuty, and then swapping the dropdown menu to Opsgenie, the configuration text box retains the same input.

**Comment by Cherrett** [comment]
PANIC Board

Update the test button logic of multiple input fields. These include but are not limited to:

Chainlink Prometheus URLs, Twilio phone numbers...

After updating the input field to accept multiple inputs, we must create a popup component with a table. This table will include the results of various API calls (one for each inputted source). See #201 and #263 for examples.

**Comment by zimaah** [comment]
Closing this ticket.

Outcome of the investigation about the comments can be found here: https://docs.google.com/document/d/1kP9MIJW2kbwoJTRejnNWq4mFxumgXt-ZlPOrVT-wAog/edit?usp=sharing

**Comment by crsfalzon** [comment]
Where needed, update installer pages' structure to better allow for larger data tables.
