### ISSUE TITLE
Unable to add Tendermint/Cosmos RPC URLs

### ISSUE THREAD

**Issue by Relyte** [SimplyVC/panic#170]
Version: v1.0.0
Browser: Firefox 99.0.1 w/o any extensions

Issue: Through the web GUI, the following fields are grayed out and cannot be interacted with:

- Tendermint RPC URL
  - Monitor toggle
  - Test button
- Cosmos Rest Server
  - Monitor toggle
  - Test button
- Prometheus Endpoint URL
  - Monitor toggle
  - Test button
- Node is Validator toggle
- Is Archive Node toggle
- Use as Data Source toggle

![image](https://user-images.githubusercontent.com/96859270/165321942-a3503971-b0d9-4a91-a8e4-68798a271b7f.png)

**Comment by dillu24** [comment]
Hey @Relyte thanks for your question. Cosmos blockchain-specific monitoring is not yet released. At the moment you can only monitor the system a node runs on through node-exporter

**Comment by Relyte** [comment]
Awesome, thanks for the quick feedback! Looking forward to the next release!

**Comment by dillu24** [comment]
Hey @Relyte just to let you know that we released cosmos node monitoring and alerting.
