### ISSUE TITLE
Web Installer outputting dockerhub configs incorrectly

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#18]
When testing out the dockerhub implementation I noticed that the schema outputted by the web-installer is incorrect. The web-installer is outputting the following schema:

```
[docker_09c56c8d-afcb-434b-8102-8cc58d39cfc3]
id=docker_09c56c8d-afcb-434b-8102-8cc58d39cfc3
parent_id=chain_name_2be935b4-1072-469c-a5ff-1495f032fefa
name=dylangalea/testrepo
monitor_docker=true
```

However the schema should look like this, where name is to be split into repo_namespace and repo_name, and monitor_repo should replace monitor_docker:

```
[docker_09c56c8d-afcb-434b-8102-8cc58d39cfc3]
id=docker_09c56c8d-afcb-434b-8102-8cc58d39cfc3
parent_id=chain_name_2be935b4-1072-469c-a5ff-1495f032fefa
repo_name=testrepo
repo_namespace=dylangalea
monitor_repo=true
```

We must also collaborate with Luke to check what should be put inside the docker forms in terms of placeholders, field descriptions, field names and so on.

**Comment by drmenguin** [comment]
Hi guys, every repo has a namespace. Usually it's the same as the username of the creator of the repository, e.g. my username on dockerhub is `lukepanictest`, and the repo namespace is `lukepanictest` (and the necessary API call that PANIC makes is on https://hub.docker.com/v2/repositories/lukepanictest/test/tags).

On the other hand, big standard repos like nginx, ubuntu, etc., large projects which tend to have the "official image" label next to them (but even others which don't) have namespace `library`.
![image](https://user-images.githubusercontent.com/19354076/148223650-b8e2fd82-0138-4684-a7cc-cb6beefaf588.png)
So for example, `python` has namespace `library` (and API URL https://hub.docker.com/v2/repositories/library/python/tags).

In the installer, I would let the user input the namespace themselves (they'll probably be monitoring small repos more than big standard ones) but put a message along the lines of "If you don't know what the namespace is, it's probably `library`, the username of the creator of the repository, or the same as the name of the repository".

**Comment by itsciccio** [comment]
@drmenguin What I did is add a regex validation that tests for `simplyvc/panic` or just `panic`. In the former case, the `namespace` is set to `simplyvc` and the `name` is set to `panic`. In the latter, the `name` is intuitively `panic`, whilst the `namespace`, since it is not provided, will be defaulted to `library`. 

In this way we are catering for all cases.

**Comment by dillu24** [comment]
@itsciccio I like the implemetation, but in the latter case I would do a pop-up saying that it will be defaulted to library/repo-name

**Comment by itsciccio** [comment]
@dillu24 done. updated the tooltip on the dockerhub form to inform the user of the naming convention. also fixed a bug which causes the dockerhub table to be empty. all now works as intended.
