### ISSUE TITLE
Mock Node Data for Substrate P1

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#202]
### Technical Story

To properly test the substrate alerting from an end-to-end point of view, we require a mocked node which replicates any data sent from a substrate node via a web-socket. This will then be used in a substrate node config and called via the Substrate API.

### Description

We first need to investigate which Substrate API endpoints we use for Node and Network alerting. Then we must check what endpoints does the API call to the Substrate nodes. These should then be replicated with mocked data while allowing this data to change during runtime. This way we can mock certain alerting scenarios as necessary.

### Requirements

- [x] **IMP**: Updated Substrate API before taking on this task.
- [x] Investigate which Substrate API endpoints we currently use for Substrate Node and Network monitoring.
- [x] Mock the calls made to the Substrate API in the form of a mocked API.
- [x] Dockerize the above while allowing runtime editing of mocked data files.
- [x] Make sure that each endpoint used within the Substrate API works with the mocked API.

### Blocked by

#150 (until put in review)

### Acceptance criteria

**Scenario**: The `Substrate Mock API` is started and receiving/sending data
**Given**:  Substrate Mock API started
**When**: Sending API requests to the Substrate Mock API
**Then**: You can see correct data returned based on the mocked data

**Scenario**: The `SubstrateNodeAlerter` is started and alerting correctly
**Given**:  PANIC started and the mock started
**When**: Checking the log files inside the `alerter/logs/alerters` and the docker-compose console
**Then**: You can see correct alerts being raised based on the mocked data

**Comment by Cherrett** [comment]
We must make sure to update the Substrate API to the latest version before carrying out any testing

**Comment by dillu24** [comment]
While doing the alerter review I ran through an example were the user might switch the node from being a validator to a non-validator and vice-versa. We should test out this behaviour to see how it behaves for all metrics. Depending on the outcome we might reset all the state (limiters, warning_sent, critical_sent etc) if the `is_validator` value changes, leave everything as is to be resolved automatically or only reset some metrics only.

![image](https://user-images.githubusercontent.com/23262259/170209629-3774bc81-8e39-4fa5-a893-79f228c877c6.png)
