### ISSUE TITLE
Installation Wizard - Content For Sources Setup

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#210]
### Rationale

When working on the _prototype_ for the installer, we implemented only one journey (Cosmos-SDK), to save us some time, but we ended up getting approval from staking team only for that base-chain journey. Most of the installer will display pretty much the same content across the steps, regardless of the base-chain being configured, although when it comes to the Sources setup (Nodes, EVMNodes, etc) there is a big difference.

### For ticket closure

- Go over the `web-installer` and gather all the texts/messages that are currently being displayed there in the "Nodes setup" step and sort it by base-chain. Missing content: Chainlink, Substrate and General.
- Content that must be listed:
   - source description (the text displayed on each card - _gray rectangle in the web-installer_)
   - inputs help message (the text displayed when you hover the info icon)
- Feel free to fix any typo or grammar error that you might spot. For example, _rpc_ should be written _RPC_ since it's an acronym :+1: 
- The outcome of this ticket is an artifact (document, excel, PDF, etc. up to the assignee) containing the current content sorted by base-chain. Once the artifact is ready @crsfalzon can step in to review the content and get approval from staking team (if necessary)

**Comment by itsciccio** [comment]
Content can be found on this [Google Docs document.](https://docs.google.com/document/d/19vzwHK8Rn50FWErxbhXfFjywiuu7C7fIZhSyraCJybw/edit?usp=sharing)

For each Chain (Cosmos, Susbstrate, Chainlink & General), you can find each step the user is presented with, alongside all descriptions and input helpers (tooltips and placeholders). I went through all the texts and amended any grammatical errors/typos.

**Comment by itsciccio** [comment]
Also included GitHub and DockerHub steps, as the descriptions might differ between one base chain and the other. Like this we have the complete user story in a single document.

**Comment by itsciccio** [comment]
@crsfalzon kindly review content + get approval from staking team (if necessary)

**Comment by itsciccio** [comment]
New UI Installer screenshots can be found on this [Google Docs Document](https://docs.google.com/document/d/1Qiytgb5hNq1IN3StQH15nKfTFwvvFI4a4tdYyxpIkN0/edit?usp=sharing).

@crsfalzon
