### ISSUE TITLE
Add Get Chain Properties Endpoint in Substrate API

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#211]
### Technical Story

As the Substrate API, I want to expose chain information/properties for a given web-socket.

### Description

Add an endpoint for retrieving chain properties within the Substrate API. An example of this can be seen [here](https://polkadot.js.org/docs/api/examples/promise/chain-info). This endpoint should return the ss58 format, the token decimals, and the token symbol.

### Requirements

~~- [ ] Create a new route within Substrate API (registy).~~
~~- [ ] Add a get chain properties endpoint within the registy API route.~~
- [x] Add a get chain properties endpoint within the RPC API route.~~
- [x] Create tests for new endpoint.
- [x] Manually test the new endpoint using various websocket sources.

### Blocked by

N/A

### Acceptance criteria

- [x] **Scenario**: The `Substrate API` started correctly
      **Given**: The `Substrate API` started
      **When**: Checking the log files inside the Substrate API docker container
      **Then**: You can see correct startup

- [x] **Scenario**: The `Substrate API` is receiving API calls
      **Given**:  The `Substrate API` is running
      **When**: Checking the log files inside the Substrate API docker container
      **Then**: You can see the correct API calls being acknowledged

- [x] **Scenario**: The `Substrate API` is responding to API calls
      **Given**:  The `Substrate API` is running
      **When**: Checking the response sent from the API
      **Then**: You can see the correct data returned

**Comment by dillu24** [comment]
We can use the `api.rpc.system.properties` endpoint to not create a registry route.
