### ISSUE TITLE
Update Channels Settings Journey - Home Page 1/3

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#213]
Story

As a node operator, I want to be able to manage my channels configurations and their respective associations with sub-chains.

### Description

Notice: the journey "update channels config" was split in **3** tickets. This is **1/3**.

The scope of this ticket is to create the "entry point" component for the update channels config functionality. It will be responsible for three things:
- fetching data from the backend
- rendering children components, namely:
   - `panic-config-channels-crud` (tackled in a separate ticket)
   - `panic-config-channels-map` (tackled in a separate ticket)
- handling navigation (back to home page) 

### Requirements
- the node operator lands on this page after clicking on Channels from the Settings dropdown https://github.com/SimplyVC/panic/issues/223
- create a component with tag name `panic-settings-channels` under `/components` folder
- it will be accessible via `/settings/channels` route (to be added at `panic-root.tsx` file)
- the visual outcome expected can be found in the screenshot attached. Must elements in the page:
   - header
   - footer
   - back button (it's not a problem to have the back button positioned differently from what's in the screenshot. When that screenshot was taken, the page had the two cards in place, I just removed them with an editor to make the scope more evident. The button's final positioning can be amended in the next tickets)
- the `render()` method must already include the JSX for the following components *
   - `panic-settings-channels-crud` (to be tackled in a separate ticket)
   - `panic-settings-subchain-map` (to be tackled in a separate ticket)
- when the node operator clicks in the "back" button, he must be redirected to `/` (home page)
- E2E test + snapshot

*Having a JSX with a component tag name that still doesn't exist won't cause any errors.

![panic-settings-channels](https://user-images.githubusercontent.com/7024585/169086335-b1e973d3-701b-4b6a-8f97-225bd74f813e.png)

### Blocked by

N/A

### Acceptance criteria

**Scenario**: The node operator lands on this page after having selected Channels from the Settings dropdown https://github.com/SimplyVC/panic/issues/223
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: He clicks in the "back" button
**Then**: He's redirected back to the Home page

**Comment by crsfalzon** [comment]
Back button not in scope - redundant
