### ISSUE TITLE
Update Channels Settings Journey - panic-settings-channels-crud Component 2/3

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#215]
Story

As a node operator, I want to be able to see the channels that I have configured and perform CRUD operations over them.

### Description

Notice: the journey "update channels config" was split in 3 tickets. This is 2/3.

The scope of this ticket is to create a stateless component called `panic-settings-channels-crud` and its responsibilities are:
- render markup for the "Channels" card
- open the add/update channel modal
- fire specific events which will be handled by `panic-settings-channels`

### Requirements

- Work out the markup for the "Channels" card as per screenshots
- If there is no channel previously added, then the channel type filter + data table aren't shown.
- Add channel button (when clicked, it will create a modal and render the _very same_ form as in the installer. We can adapt and reuse it :bulb:)
- Channel types filter (when the value changes, it will emit an event called `onChannelTypeChange` which will be handled by `panic-settings-channels`)
- A data table to display the configured channels
   - When the "Enabled" checkbox is clicked, it will emit an event called `onEnable` which will be handled by `panic-settings-channels`)
- When the form displayed in the modal is submitted (either when adding/updating), an event called `onSave` will be fired along with the channels' data (when necessary) and it will be handled by `panic-settings-channels`

![panic-settings-channels-crud](https://user-images.githubusercontent.com/7024585/169279590-636ce667-6ff8-483a-b5ea-709d8a5ae0bd.png)
![panic-settings-channels-crud-nodata](https://user-images.githubusercontent.com/7024585/169279593-f69329ff-5bd8-4ce5-9444-683442493dbe.png)

### Suggestions/Thoughts

- If when starting this ticket the required endpoints are still not ready, just mock the API calls (you can create a JSON file somewhere and literally make `fetch()` it)
- To facilitate the review flow, I would suggest to first work out your commits starting from the UI aspect of the ticket (markup + CSS only). Work on it in "isolation", make sure that from a visual perspective the requirements are met. Once you have this part done, you are able to open the MR and someone can start reviewing this ticket.
- Once the UI part is committed, you can continue to work on the logic related to the different elements on the page.

### Blocked by

(https://github.com/SimplyVC/panic/issues/213)

### Acceptance criteria

**Scenario**: Listing channels (no data)
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: The page loads
**Then**:  He sees only a button to add a new channel (see screenshot for reference)

**Scenario**: Listing channels (with data)
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: The page loads
**Then**:  He sees the previously added channels, along with a button to add more and a channel type filter (see screenshot for reference)

**Scenario**: Add new channel
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: He clicks in the "add channel" button
**Then**:  A modal is shown with containing all necessary fields to config a channel

**Scenario**: Update channel
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: He clicks in the "edit channel" button
**Then**:  A modal is shown with containing a form filled with data from the respective channel being edited

**Scenario**: Delete channel
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: He clicks in the "delete channel" button
**Then**:  A confirmation alert is shown asking whether he wants to proceed with the action

**Scenario**: Filtering channels by channel type
**Given**: The node operator has accessed the channels settings page via Settings > Channels menu
**When**: He chooses a specific channel type in the filter
**Then**:  The data table is updated accordingly to the filter selected

**Comment by dillu24** [comment]
enabled functionality not required by alerter.
