### ISSUE TITLE
Investigation into #155

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#279]
### Rationale
#155 was used to keep track of notes to action with regards to the 2nd iteration of the UI. We need to go through the various comments to:
1. understand which comments need to be worked on.
2. Identify any dependencies to implementation.

### For ticket closure
The outcome of this task is:
1. a set of tickets that will allow for the closure of #155. If necessary, specify any dependencies by using the 'Blocked by' section and label.
2. a presentation of the findings to the team.

**Comment by zimaah** [comment]
PANIC - Enforce Base Chain In The Form
https://docs.google.com/document/d/1CoCwfpINIeccLARKL7VfNS3KHOjWmw38s8mbxrf0i_g/edit

**Comment by zimaah** [comment]
PANIC - Load Base Chain Entity
https://docs.google.com/document/d/1LYZMhOWpuREVm7ere7Kp1IH3A5L7chhN4CMKe2p46iU/edit

**Comment by zimaah** [comment]
Investigation outcome (tickets that I should create)

- https://docs.google.com/document/d/1LYZMhOWpuREVm7ere7Kp1IH3A5L7chhN4CMKe2p46iU/edit PANIC - Load Base Chain Entity
- https://docs.google.com/document/d/1CoCwfpINIeccLARKL7VfNS3KHOjWmw38s8mbxrf0i_g/edit PANIC - Enforce Base Chain In The Form
- https://docs.google.com/document/d/171wdMoMbvF1ziYDyICCTPBycx8ae8V1t0Q2xg7KfuqU/edit PANIC - Warn User About Losing Form Data
- https://docs.google.com/document/d/12-m9UN-qk44QDowvA8V06kfS6cSl31eqk8I7YvIFUMU/edit PANIC - Display Warning If No Channels Added
- https://docs.google.com/document/d/1MNXH8PnO-QUvmM22pQtuNSKHfzpP9a3_B-hbbGF0yTg/edit PANIC - Types Definition (TS)
