### ISSUE TITLE
Develop a Config files <-> Database migration script

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#281]
### Technical Story

The old web-installer used to save configurations inside configuration files. With UI iteration 2 we are now saving configurations inside a MongoDB. In addition to this the configuration data structure changed.

As a user I want that this migration happens as smoothly as possible.

### Description

The aim of this task is to develop a script which performs this migration

### Requirements

- [x] Create a functionality which migrates Chainlink configurations to MongoDB
- [x] Create a functionality which migrates Cosmos configurations to MongoDB
- [x] Create a functionality which migrates Substrate configurations to MongoDB
- [x] Create a functionality which migrates General configurations to MongoDB
- [x] Create a functionality which migrates all Channel configurations to MongoDB
- [x] The script deletes the entire `Config` folder once the migration occurs

### Blocked by 

N/A

### Acceptance criteria

**Given**: A set of Chainlink configurations
**Then**: The Chainlink base chain folder is deleted and the configurations are migrated correctly to the database

**Given**: A set of Cosmos configurations
**Then**: The Cosmos base chain folder is deleted and the configurations are migrated correctly to the database

**Given**: A set of Substrate configurations
**Then**: The Substrate base chain folder is deleted and the configurations are migrated correctly to the database

**Given**: A set of General configurations
**Then**: The General base chain folder is deleted and the configurations are migrated correctly to the database

**Given**: A set of Channel configurations
**Then**: The Channel folder is deleted and the configurations are migrated correctly to the database

**Comment by itsciccio** [comment]
We need to do the same for channels as well, updating description
