### ISSUE TITLE
Remove Legacy Installer

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#287]
### Technical Story

As PANIC, I no longer require the legacy installer since the new UI interface contains the installer to be used.

### Description

Since we are moving away from the legacy installer. This should be removed before releasing. Besides removing the `web-installer` directory, we must also make sure that PANIC builds without it. Further details can be found in the requirements below.

### Requirements

- Remove the `web-installer` directory and its content
- Remove the `installer` service from `docker-compose.yml`
- Remove any redundant ENV variables from `.env`
- Remove installer-related documentation since this will be replaced with documentation for the new installer journey
- Remove any redundant entires in `.gitignore` and `.dockerignore`
- Update any CI/CD configurations accordingly

### Blocked by

Should be tackled at the end of UI Iteration 2, so https://github.com/SimplyVC/panic/issues/347

### Acceptance criteria

**Scenario**: Running PANIC
**Given**: Built and raised PANIC docker containers
**When**: No errors are shown
**And**: Installer container is not built and raised
**Then**: PANIC should build and run without any errors/interruptions

**Comment by dillu24** [comment]
Just remove from docker-compose .. we need to also remove the configs from the docker volumes.
