### ISSUE TITLE
Hotfix - Installer - Blank page when adding a cosmos node

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#294]
### Summary of bug

When adding a Cosmos node within the installer, a blank screen is shown. The following can be seen in the browser's console:

![image](https://user-images.githubusercontent.com/49488952/176687852-07bd8157-1b07-463f-b256-4ec545750636.png)

### 'As is' behaviour 

Blank screen after adding a cosmos node.

### 'To be' behaviour

Node is added successfully after adding a cosmos node.

### Steps to reproduce

Run the installer, set up a cosmos subchain and attempt to add a node.

### Acceptance criteria

**Given**: PANIC Installer is running
**When**: Adding a node to a cosmos sub-chain
**Then**: Node is added successfully

**Comment by Cherrett** [comment]
I can confirm that this only occurs for cosmos nodes.

**Comment by Cherrett** [comment]
From the initial investigation, looks like a change in `web-installer/src/components/chains/common/forms/monitorNetworkNodesForm.js` might have caused this bug.

**Comment by irs111** [comment]
I confirm this issue too. Fresh installation, blank screen right after clicking add cosmos node.

**Comment by dillu24** [comment]
Hi @irs111 we are currently investigating, hopefully it is nothing major so we publish a hotfix asap
