### ISSUE TITLE
Installer error when loading config

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#295]
### Summary of bug

Timo reported that when loading the configurations in the installer the following error is raised:

![image](https://user-images.githubusercontent.com/23262259/177096845-b983049d-a743-4f61-831d-11b9cda52699.png)

In addition to this, the previously set up slack channel configuration was deleted. This could mean that the installer was not able to load the slack configuration.

### 'As is' behaviour 

The installer is failing to load the configurations

### 'To be' behaviour

The installer should be able to load all types of configurations without deleting any previously set up config

### Steps to reproduce

Not sure whether we are going to be able to replicate this, but we should try out the following:

1. Set up a slack configuration
2. Close installer
3. Open installer
4. Load previously set up configs

### Acceptance criteria

**Given**: The user re-loads the installer with a slack config set up
**When**: Clicking on the load existing configs functionality
**Then**: All configurations are loaded successfully

**Comment by crsfalzon** [comment]
Discuss with Timo to replicate. Get configs, logs, ...

**Comment by itsciccio** [comment]
The issue was due to the `[]` (square brackets) within the input names. Pushing a hotfix to not allow the user to submit the respective forms if such a character is inputted.
