### ISSUE TITLE
PANIC - Load Base Chain Entity

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#298]
### Technical Story

As a PANIC UI, I want to have the list of base-chains loaded from the API at the very beginning of my bootstrapping process, so I can consider the application loaded only if this very important step succeeds.

### Description

Currently, in the solution present feature/ui_iteration_2, we don’t have an standardized way of fetching the list of base-chains (it’s scattered across different pages in the installer), and we are not loading it at the very beginning (in the panic-root component) nor ensuring that the app is considered loaded only if this very important step succeeds (since this information is used across the product).

The improvement described in this ticket must be tackled in the installer context only. The rest of the app (home page logic) will be amended in a different moment.

See the Requirements section for more info.

### Requirements

Come up with a strategy/approach (ideally following patterns) for communication with the API. See the code under /src/services *
Load the list of base chains following the new API endpoint (check Swagger docs before going anywhere else for help. If the docs aren’t that helpful, feel free to ask for help.)
Make the call to the API in the componentWillLoad() from the panic-root component. Here, we need to create a logic that considers the application loaded only if this very important step succeeds. **
Update/create tests as required
Update/create documentation as required
Remove obsolete code as required

* I did an implementation that caters for that in the Add Sources ticket, meaning it’s already available in the feature/ui_iteration_2 branch. It’s something similar to what Rider did in the backend in terms of parsing entities, exposing services, etc. This should not be taken for granted, meaning that the developer who is going to tackle this improvement needs to understand what’s happening there, evaluate it and decide if the solution is good or not, improve it or come up with something better.
** There is something already there for this item too. As above, it needs to be evaluated against the requirements.

### Acceptance criteria

Loading PANIC UI with API down (not working)
Given: The node operator has accessed the home page
When: The API is down
Then: An info alert saying something like “The API service is not working, please restart PANIC UI.” is shown

Loading PANIC UI with API working normally
Given: The node operator has accessed the home page
When: The API is OK
Then: The home page is loaded as usual

**Comment by crsfalzon** [comment]
Replicated - already done
