### ISSUE TITLE
PANIC - Warn User About Losing Form Data

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#300]
### User Story

As a node operator, during the installation journey, I want to be warned if I try to navigate away from a form, so I don’t lose any information that hasn’t been saved yet.

### Description

After performing the investigation in #332 we concluded the following:

- Having a modal each time popping up whenever the user is about to navigate away from a page is no longer required because we no longer have forms embedded on a page, but forms embedded on a pop-up. Therefore, the user can't navigate away from a form unless they click cancel .. in which case it is understandable that the data is lost.
- There is only 2 forms embedded directly with a navigation, the subchain page of the installer and the alerts page of the installer. In case of the subchain page, you only loose the data whenever you click back, in which case this is not a big deal as you only need to enter the subchain name. In the case of the alerts page what we can do is create an isModified boolean field which by default is set to false in the form such that whenever one of the entries is modified, isModifed is set to true. If isModified is set to true a pop up is shown on back asking the user if they want to save before proceeding further.
- Another thing worth fixing is to disable every modal from being closed whenever the user clicks outside of the modal. Like this we can prevent the user from loosing data if they accidently click outside of the modal. See https://forum.ionicframework.com/t/ionic-dismiss-modal-when-click-outside-of-element/172762/2

### Requirements

- [ ] (see respective comment) ~~Implement `isModified` functionality on the alerts page for every basechain.~~
- [x] Implement `Do you want to save` popup and its logic.
- [ ] (see respective comment) ~~Disable modal closing when clicking on the background page for every modal.~~

### Acceptance criteria

PANIC UI Installer - Alerts page (Substrate)
Given: The node operator is in the substrate alerts page
When: The node operator modifies a field and navigates using back
Then: A popup requesting the user to save or not is shown
When: The user clicks yes
Then: The alerts are saved and the node operator is navigated to the previous page
When: The user clicks no
Then: The configs are not saved and the node operator is navigated to the previous page

PANIC UI Installer - Alerts page (Chainlink)
Given: The node operator is in the chainlink alerts page
When: The node operator modifies a field and navigates using back
Then: A popup requesting the user to save or not is shown
When: The user clicks yes
Then: The alerts are saved and the node operator is navigated to the previous page
When: The user clicks no
Then: The configs are not saved and the node operator is navigated to the previous page

PANIC UI Installer - Alerts page (Cosmos)
Given: The node operator is in the Cosmos alerts page
When: The node operator modifies a field and navigates using back
Then: A popup requesting the user to save or not is shown
When: The user clicks yes
Then: The alerts are saved and the node operator is navigated to the previous page
When: The user clicks no
Then: The configs are not saved and the node operator is navigated to the previous page

PANIC UI Installer - Alerts page (General)
Given: The node operator is in the geenral alerts page
When: The node operator modifies a field and navigates using back
Then: A popup requesting the user to save or not is shown
When: The user clicks yes
Then: The alerts are saved and the node operator is navigated to the previous page
When: The user clicks no
Then: The configs are not saved and the node operator is navigated to the previous page

Given: Any modal
When: The node operator clicks outside the modal
Then: The modal is never closed

**Comment by dillu24** [comment]
Scope of ticket changed as per investigation outcome here: https://github.com/SimplyVC/panic/issues/332

**Comment by itsciccio** [comment]
Regarding the first requirement:

```Implement isModified functionality on the alerts page for every basechain```

The issue with this logic would be understood by the following example:

1. Node operator presented the alerts setup page.
2. Node operator unchecks a checkbox for an alert.
3. Node operator re checks the checkbox for the previously unchecked checkbox.
4. The `isModified` logic remains as true. Therefore the warning popup will still be shown even though no changes had been made.

The alternative approach is to load the alert data from the API and compare the current form data with that from the API in order to understand if any changes were made. However, this requires a component overhaul with the new data types from the API, something that is to be tackled in https://github.com/SimplyVC/panic/issues/309.

For this reason, we will be ignoring this requirement in this ticket, and will be tackled in the linked ticket once the component is updated to suit the updated API.

**Comment by itsciccio** [comment]
Regarding the third requirement:

```Disable modal closing when clicking on the background page for every modal.```

This fix must be done on the UIKit project. Will open a ticket soon on that board.
