### ISSUE TITLE
Installer - API & Types Definition Update 3/5 (Repos)

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#308]
### Technical Story

As a PANIC UI developer, I want to have proper “types” (TS interfaces, classes and types) and API calls (made to the real endpoints), so I can understand the code better and finish off each step in the installer.

### Description

We tackled the work in the new installer in a very asynchronous way, meaning that when we were implementing parts of the frontend we didn't have **real endpoints & types** available to be consumed, and basically we had to mock logic (types, API calls, etc.) as necessary to get the ticket requirements done.

Now we have our types (TS interfaces, classes and types) ready to be consumed across the UI logic, so we need to go end-to-end in the installer code and update the props/vars/consts/params/etc to use the proper type's definition located at _panic/entities/ts_. **This ticket covers the Repos step only.**

- **types**: check _panic/entities/ts_ folder
- **API**: check the _swagger.json_ file under _panic/api/src_

_**If you spot anything "off" in the data types and/or API, please make a note and raise your concern asap, so we discuss and fix it accordingly.**_

### Requirements

- **Ticket scope: Repos step only**
- Update all type definitions for entities to use the equivalent present at _panic/entities/ts_ 
- Update all API calls as necessary
- Everything related to code being updated/amended must be **hard-tested**, to ensure that the functionality remains stable. Any issue/bug must be resolved before merging this ticket.

_Type update example_
![image](https://user-images.githubusercontent.com/7024585/177292772-5b866cdb-1552-403f-9e6b-3d62f7380ff0.png)

### Acceptance criteria

Checking PANIC UI source code
Given: The PANIC developer checks the source code for the installer
When: The code is shown
Then: The developer can verify that all types definitions are using the ones present at _panic/entities/ts_ **and** all API calls are being made to the **real endpoints**

**Comment by crsfalzon** [comment]
The scope of this ticket covers both repos setup during installation, and editing of repo configs.

**Comment by itsciccio** [comment]
TODO: input validation for dockerhub repos: enforce `string/string` format with regex expression `^[a-z+-0-9]+\/[a-z+-0-9]+$|^[a-z+-0-9]+$`

Error message: `Name must be in the form 'simplyvc/panic' or 'panic'.`

**Comment by itsciccio** [comment]
Regarding the above comment...

https://github.com/SimplyVC/panic/issues/340

**Comment by dillu24** [comment]
Blocked by #319 until we merge it.
