### ISSUE TITLE
Installer - API & Types Definition Update 4/5 (Alerts)

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#309]
### Technical Story

As a PANIC UI developer, I want to have proper “types” (TS interfaces, classes and types) and API calls (made to the real endpoints), so I can understand the code better and finish off each step in the installer.

### Description

We tackled the work in the new installer in a very asynchronous way, meaning that when we were implementing parts of the frontend we didn't have **real endpoints & types** available to be consumed, and basically we had to mock logic (types, API calls, etc.) as necessary to get the ticket requirements done.

Now we have our types (TS interfaces, classes and types) ready to be consumed across the UI logic, so we need to go end-to-end in the installer code and update the props/vars/consts/params/etc to use the proper type's definition located at _panic/entities/ts_. **This ticket covers the Alerts step only.**

- **types**: check _panic/entities/ts_ folder
- **API**: check the _swagger.json_ file under _panic/api/src_

_**If you spot anything "off" in the data types and/or API, please make a note and raise your concern asap, so we discuss and fix it accordingly.**_

### Requirements

- **Ticket scope: Alerts step only**
- Update all type definitions for entities to use the equivalent present at _panic/entities/ts_ 
- Update all API calls as necessary
- Everything related to code being updated/amended must be **hard-tested**, to ensure that the functionality remains stable. Any issue/bug must be resolved before merging this ticket.

_Type update example_
![image](https://user-images.githubusercontent.com/7024585/177292772-5b866cdb-1552-403f-9e6b-3d62f7380ff0.png)

### Acceptance criteria

Checking PANIC UI source code
Given: The PANIC developer checks the source code for the installer
When: The code is shown
Then: The developer can verify that all types definitions are using the ones present at _panic/entities/ts_ **and** all API calls are being made to the **real endpoints**

**Comment by crsfalzon** [comment]
The scope of this ticket covers both the review and setup of alerts during installation, and later editing of alert configs.

**Comment by itsciccio** [comment]
We also need to perform a check for changes in the alerts forms in order to alert the node operator if form contains unsaved changes upon navigation. See https://github.com/SimplyVC/panic/issues/300#issuecomment-1201008052 for a better explanation.

**Comment by dillu24** [comment]
It was agreed that we should put the `Network Monitoring` field beneath the CRUD data table and centered for every base-chain.

![image](https://user-images.githubusercontent.com/23262259/186138010-13ce385a-a0d4-4678-8e66-d66921f37091.png)

**Comment by dillu24** [comment]
We need to fix a bug on field validation for sources with empty URL when the `Monitor` switch is off. We need to check this for other fields such as the `Operator Address` for Cosmos.

I suggest we go over each form and check that the validation is correct

**Comment by itsciccio** [comment]
Included the above changes (https://github.com/SimplyVC/panic/issues/309#issuecomment-1223884834, https://github.com/SimplyVC/panic/issues/309#issuecomment-1224270541) in my branch.
