### ISSUE TITLE
Monitors - Adapt Node Monitors Manager for Cosmos

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#31]

**Comment by dillu24** [comment]
The Node Monitors Manager must be modified such that it can start Cosmos Node Monitors based on the given configuration.

For each sub-configuration, a monitor is started only if the following are satisfied:

- The node being monitored has at least one enabled endpoint (prometheus, cosmos rest or tendermint rpc), and monitor_node is set to True.
- There is at least 1 data source irrespective of what endpoints were enabled/disabled and their value. Data sources should be grouped as [non-validators, validators, node-being-monitored (even if use as data source is false, as this is a last resort attempt by the monitor)]

See implementation of Substrate for an idea.
