### ISSUE TITLE
Update content for Nodes setup info button

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#311]
### Summary of bug
When doing node setup for **Cosmos and Substrate base chains** (step 3 of 5), we show an info button next to the text, 'Here you will configure the nodes you want monitored and triggering alerts' we show an info button which when clicked presents the node operator with a popup covering two sections - Basics and Tips (see below). The content of both sections needs some minor adjustments. 

![installer step 3 of 5 - info popup improvements](https://user-images.githubusercontent.com/89395527/178233600-bf6fa365-d2b5-489f-903c-e642d767828c.PNG)

### 'As is' behaviour 

- The first line of the Basics section reads, "This is the node's setup step, here you will configure the node you want monitored and alerted on". 
- The last line of the Tips section reads, "Do not use [] in your names as you will not be able to load the configuration".

### 'To be' behaviour

- The first line of the Basics section should read, "This is the node's setup step, here you will configure the node you want **to be** monitored and alerted on". 
- Update the content of the Tips section to read, "We suggest to add the IP Address to the node name so you know where to look for the node. For example, cosmos_main_validator(IP)". The example node name shown should be representitve of base chain. So if for example, the node operator is setting up a substrate node, then the example would read, "polkadot_main_validator(IP)".
- When showing the node name use monospace font & secondary colour.

### Steps to reproduce
1. Get to step 3 of 5 of the installation process.
2. Click on the info button next to the text, 'Here you will configure the nodes you want monitored and triggering alerts'.

### Acceptance criteria
**Given**: The node operator is on step 3 of 5 in the installation process.
**When**: He clicks on the info button
**Then**: He is presented with updated content as per above.

**Comment by itsciccio** [comment]
This requirement was omitted.

```When showing the node name use monospace font & secondary colour.```
