### ISSUE TITLE
Update PANIC UI with latest UI Kit version

### ISSUE THREAD

**Issue by itsciccio** [SimplyVC/panic#313]
### Technical Story

As PANIC UI, I want to have the latest version of the UI Kit, so that I can make use of required components.

### Description

We must update the UI Kit version used by PANIC UI. This must be done by modifying the code in respect to breaking changes. Features such as amending the `svc-data-table` to return the object instead of the index of the row need to be implemented. Refer to the latest UI Kit changelog for a full list of new features.

### Requirements

- Update to latest UI Kit version within PANIC UI
- Fix any breaking changes
- Adapt code to cater for multiple inputs where required
- Test out PANIC UI to confirm it is still functional throughout

### Blocked by

N/A

### Acceptance criteria

**Given**: PANIC UI started and built without any errors
**When**: All pages within PANIC UI are used
**Then**: PANIC UI functions as intended

**Comment by crsfalzon** [comment]
Waiting for the release of UI Kit v1.5.0
