### ISSUE TITLE
API: Create all Channel Config endpoints for UI

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#319]
### Technical Story

The **node operator** needs to specify config ID and channel ID to link or unlink a given config (subchain) with a given channel.

### Description

Further endpoints should be added to the Channel Resource/Route. Said endpoints are:

- `/channels/{channel-id}/configs/{config-id} POST` to link a channel to a config (sub-chain)
- `/channels/{channel-id}/configs/{config-id} DELETE` to unlink a channel from a config (sub-chain)

### Requirements

- [x] Add required logic/functions to cater for linking/unlinking behaviour es explained above
- [x] Add the two endpoints as explained above
- [x] Update channels family in swagger to cater for endpoints above and to remove any redundant endpoints (Config > Channel family)
- [x] On delete config, delete any references from channels
- [x] Create any unit tests as required

### Blocked by

#320 

### Acceptance criteria

Scenario: The API user wants to create a link between a channel and a subchain
Given: API is running and a subchain is setup
When: I request `/v1/channels/{channel-id}/configs/{config-id}` by POST method
Then: I will create a link between the given channel and the given subchain

Scenario: The API user wants to remove the link between a channel and a subchain
Given: API is running and a subchain is setup
When: I request `/v1/channels/{channel-id}/configs/{config-id}` by DELETE method
Then: I will remove the link between the given channel and the given subchain

Scenario: The API user wants to see API docs via swagger
Given: API is running
When: I access api-docs to see swagger API documentation
Then: Newly created channel config endpoints are properly detailed in swagger API documentation and redundant endpoints are not shown

**Comment by crsfalzon** [comment]
Change in ticket scope. Keep only POST from the list above and include DELETE
