### ISSUE TITLE
Investigate requirements of BaseChains API V1 endpoints + functionality on all endpoints

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#327]
### Rationale

The scope of this ticket is to investigate from the UI-perspective which basechains API endpoints are required (#324) and whether filtering, sorting, and pagination is required on all endpoints (#325).

In regards to basechains API endpoints, we need to investigate whether the following endpoints are required:

- [x] `/v1/basechains` by GET method to get all basechains
- [x] `/v1/configs/basechains` by GET method to get setup basechains (basechains used)
- [x] `/v1/configs/basechains/{basechain-id}` by GET method to get a specific basechains

In regards to functionality, we need to investigate whether the following features are required:

- [x] Filtering
- [x] Sorting
- [x] Pagination
- [x] Whether the above should be applied to some or all V1 endpoints

### For ticket closure

- [x] Justify outcome from the UI perspective and discuss it with team
- [x] Create/Modify tickets as required based on the result of this investigation

**Comment by dillu24** [comment]
The scope of this ticket was modified:

1. Ignore pagination, filtering and sorting for now as they are nice to haves
2. We will go through the list of endpoints required for every family in a meeting
