### ISSUE TITLE
API: Update configs endpoints with new requirements

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#328]
### Technical Story

From #327, we came up with further requirements for the configs endpoints. This includes changes to the POST endpoint which includes changing the return body, ~~functionality for loading alerts/thresholds~~, and for creating a ready flag property. ~~Moreover, this ticket also includes the creation of a new endpoint which is responsible for marking a given config as done~~.

### Description

The changes required to existing configs endpoints are described below:

- [x] `/configs POST` returns the ID of the newly created config
~~- [ ] `/configs POST` loads the list of alerts/thresholds in the config, based on the basechain passed~~
- [x] `/configs POST` creates a ready flag property within the config object

Moreover, the following endpoints must be created:

~~-  [ ] `/configs/{config-id}/done PUT` sets the ready flag to true for the given config~~ **This is no longer needed as we can use the already implemented `v1/configs/{config-id} PUT` endpoint without having to send the entire configuration.**

### Requirements

- [x] Add required logic/functions to cater for changes and additions as explained above
- [x] Modify `/configs POST` endpoint
~~- [ ] Add `/configs/{config-id}/done PUT` endpoint as explained above~~
- [x] Update configs family in swagger to cater for modifications/additions to the endpoints
- [x] Create/modify any unit tests as required

### Acceptance criteria

- [x] Scenario: The API user wants to get ID of a new config
Given: API is running
When: I request `/v1/configs` by POST method
Then: I will create a a new config and its ID will be returned

- [x] Scenario: The API user wants to create a new config
Given: API is running
When: I request `/v1/configs` by POST method
Then: I will create a new config and it includes the ready flag property

- [x] Scenario: The API user wants to mark config as ready/done
Given: API is running and config was created
When: I request `/v1/configs/{config-id}` by PUT method
Then: The config with the given config ID is marked as done (ready prop is true)

- [x] Scenario: The API user wants to see API docs via swagger
Given: API is running
When: I access api-docs to see swagger API documentation
Then: Newly created/modified endpoints are properly detailed in swagger API documentation

**Comment by dillu24** [comment]
At the moment this ticket is blocked due to the following:

1. For the completed tasks I still need to confirm that the endpoint works as expected. At the moment I can't test as there is some validation issue in the Configs endpoints family. @simplyrider should be investigating this.
2. Adding the list of alerts to the basechain might not be the optimal way as this means the list of alerts will be duplicated inside the Config entity. Therefore, we need to determine how it is best to list the alerts. Note that the outcome of this discussion will effect both #330 and #329 

Some options for 2 are the following:

- We keep both the `threshold-alerts` and `severity-alerts` endpoints and have the following structure for each alert inside the generic collection:

```python
{
  "status": 200,
  "result": [
    {
      "id": "62656ebafdb17d641746dcda",
      "status": true,
      "created": "2022-04-01T00:00:00.000Z",
      "modified": "2022-04-01T00:00:00.000Z",
      "name": "Cannot access validator",
      "value": "cannot_acccess_validator",
      "description": "If a validator is a inaccessible you will be alerted."
      "basechain: {cosmos_basechain_object}"
      "warning": {
          "enabled": true,
          "repeat": false,
          "interval": 60
       },
       "critical": {
          "enabled": true,
          "repeat": true,
          "interval": 60
       }
    }
    {
      "id": "62656ebafdb17d641746dcda",
      "status": true,
      "created": "2022-04-01T00:00:00.000Z",
      "modified": "2022-04-01T00:00:00.000Z",
      "name": "Cannot access validator",
      "value": "cannot_acccess_validator",
      "description": "If a validator is a inaccessible you will be alerted."
      "basechain: {chainlink_basechain_object}"
      "warning": {
          "enabled": true,
          "repeat": false,
          "interval": 60
       },
       "critical": {
          "enabled": true,
          "repeat": true,
          "interval": 60
       }
    }
    {
      "id": "62656ebafdb17d641746dcda",
      "status": true,
      "created": "2022-04-01T00:00:00.000Z",
      "modified": "2022-04-01T00:00:00.000Z",
      "name": "Cannot access validator",
      "value": "cannot_acccess_validator",
      "description": "If a validator is a inaccessible you will be alerted."
      "basechain: {substrate_basechain_object}"
      "warning": {
          "enabled": true,
          "repeat": false,
          "interval": 60
       },
       "critical": {
          "enabled": true,
          "repeat": true,
          "interval": 60
       }
    }
  ]

```

Note that the endpoints must then be converted to `v1/threshold-alerts/{base-chain-id}` and `v1/severity-alerts/base-chain-id}` respectively.

- Remove the `threshold-alerts` and `severity-alerts` endpoints as already agreed upon, remove the `severity` and `threshold` fields from the config and add them solely to the basechain field. (For this option @Cherrett highlighted that we may modify the generic collection and create confusion)

**Comment by dillu24** [comment]
We decided the following:

1. We will keep the `v1/treshold-alerts` and `v1/severity-alerts` endpoints along with their existing data structure
2. We need to create a basechains collection having all the basechains
3. The basechains collection will have a reference to the list of threshold and severity alerts along with their default values
4. We should implement the `v1/basechains` and `v1/basechains/{basechain-id}` endpoints
5. The config response should not show the `severity` and `threshold` alerts from the base chain structure to avoid having a huge object being sent to the UI

**NOTE**: 1-5 above will be tackled in other tickets
