### ISSUE TITLE
API: Add basechains family endpoints

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#330]
### Technical Story

We need to add the base chains family endpoint to query information about the base chains.

### Requirements

- [x] Add `v1/basechains` endpoint which should return a list of all base chains supported by PANIC
- [x] Add `v1/basechains/{base-chain-id}` to return information about a selected base chain
- [x] Modify the `basechain.json` file so that developers can populate the base chain collection easily
- [x] Update `swagger.json` accordingly

## Blocked by
#328

### Acceptance criteria

**Given**: A request to the `v1/basechains` endpoint
**Then**: A list of basechains with the required schema are given

**Given**: A request to the `v1/basechains/{cosmos-id}` endpoint
**Then**: The cosmos basechain is returned with the correct schema

**Given**: A request to the `v1/basechains/{substrate-id}` endpoint
**Then**: The substrate basechain is returned with the correct schema

**Given**: A request to the `v1/basechains/{chainlink-id}` endpoint
**Then**: The chainlink basechain is returned with the correct schema

**Comment by Cherrett** [comment]
It was decided that the `v1/basechains` endpoint should return a list of all base chains supported by PANIC not just the list of base chains enabled to PANIC.
