### ISSUE TITLE
Every modal must be non-closable when clicking on background

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic#335]
### Technical Story

As a user I want that my configurations are not lost when I accidently click on the modal background

### Requirements

- Use latest release from PANIC UI kit to perform the fix on every modal

### Blocked by

#336 

### Acceptance criteria

**Given**: Any Modal
**When**: I click on the background
**Then**: The modal is not closed

**Comment by itsciccio** [comment]
I suggest going through the entire PANIC UI and applying this fix to each modal, mainly those that include user input (forms).

**Comment by itsciccio** [comment]
We also need to investigate the case of when the user hits `ESC` on their keyboard. After implementing the fix that this ticket covers, please test if the modal still closes upon `ESC` is hit on the keyboard. If closes, we need to investigate from the UI Kit side.
