### ISSUE TITLE
Update PANIC UI with UI Kit version 1.6.0

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#336]
### Technical Story

As PANIC UI, I want to have the latest version of the UI Kit.
### Description

The scope of this ticket is to update PANIC to the final version of the UI Kit.

### Requirements

- Update to latest UI Kit version within PANIC UI
- Fix any breaking changes
- Test out PANIC UI to confirm it is still functional throughout

### Blocked by

The release of UI Kit v1.6.0

### Acceptance criteria

**Given**: PANIC UI started and built without any errors
**When**: All pages within PANIC UI are used
**Then**: PANIC UI functions as intended

**Comment by itsciccio** [comment]
updated to `1.6.1` due to hotfix
