### ISSUE TITLE
Test channel alerting

### ISSUE THREAD

**Issue by itsciccio** [SimplyVC/panic#364]
### Description

We need to assert that each channel correctly receives alerts from PANIC.

### Requirements

The following must be repeated for every channel: 

- [ ] Obtain a valid channel configuration of that type.
- [ ] Run PANIC, and add the channel to a **valid** sub-chain configuration via the UI interface.
- [ ] Check that alerts are correctly being raised by the channel from the logs as well as from the channel itself (ex: Slack channel)

### Acceptance criteria

**Scenario**: Checking for alerts on a particular channel
**Given**: A valid channel configuration is associated with the sub-chain
**When**: An alert is raised by PANIC
**Then**: An alert is recieved on the particular channel being tested

**Comment by zimaah** [comment]
Tested each and every channel type by:
- Clicking in the test button
- Checking the logs for errors

Nothing abnormal has been found in the logs and during the tests via test button all of them return a positive feedback.
