### ISSUE TITLE
Detect PANIC First Installation

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#41]
**Background**

We need to come up with a logic to detect if it's the very first time that PANIC UI is running, so we can trigger the modal inviting the user to kick off the installer.

Suggestion to whoever is tackling this: I think that we can have a quick meeting to discuss the approach.

**Requirements**

A flag somewhere saying _"Hey, this is the first time running!"_.
The flag must be accessible from the service PANIC UI.

**Comment by crsfalzon** [comment]
To be done before #42
