### ISSUE TITLE
First Installation Modal

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#42]
As a node operator, I want to be prompted to start the wizard when accessing PANIC UI home page for the first time.

**Requirements**

- read the value `IS_FIRST_INSTALLATION` from https://github.com/SimplyVC/panic/issues/41
- open a modal with a brief message (explaining what's about to happen) + a button so the user can start the wizard
- while the _first configuration_ isn't concluded with success, the node operator **must not** be able to access any page **and** the modal should be always shown on the home page

**Comment by dillu24** [comment]
![image](https://user-images.githubusercontent.com/23262259/157639761-31eefd20-4488-4429-9d32-dc1395ddd41b.png)
