### ISSUE TITLE
Installation Wizard - Add Nodes

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#48]
As a node operator, I want to be able to add nodes that I want to monitor.

**Requirements**

- A "home page" for Nodes setup must be created and be displayed at _/installation/nodes_.
- The page must have two central elements:
   - A button with the label "Add Node", allowing the node operator to click and open the form. The form will be shown in a modal (no redirection to a different page).
   - A **svc-data-table** which is only rendered when the node operator has added at least one node. The data table will be set to **crud** mode, therefore rendering two buttons, for editing/deleting respectively:
      - When the node operator clicks in the "edit" button, a modal is shown with a form populated with the node data.
      - When the node operator clicks in the "delete" button, a dialog is shown asking the node operator to confirm the action.
- The page must have other 3 secondary elements:
   - A "go back" button. It leads the node operator to the previous step (Channels).
   - A "next" button. It leads the node operator to the next step (Repositories).
   - When the "next" button is clicked, the current configuration is saved in the local storage (browser cache)
   - A "help" button so the node operator can click and get to know more information about what he's configuring at the moment. This in-depth info must be displayed in a modal.

**Comment by zimaah** [comment]
Notice: in the prototypes some icons are missing in the footer, stick with what we have currently for PANIC UI.


![image](https://user-images.githubusercontent.com/7024585/159024669-c7eaf7aa-06a3-4024-b698-8db820ea9498.png)

**Comment by zimaah** [comment]
When the user clicks in the info icon.

![image](https://user-images.githubusercontent.com/7024585/159024888-fa5b7efb-0952-4526-bb76-01bde9deed3c.png)

**Comment by zimaah** [comment]
When the user clicks in the "Add Node" button.

![image](https://user-images.githubusercontent.com/7024585/159024986-d3089bff-21de-47fc-ab27-81af08167fb1.png)

**Comment by zimaah** [comment]
When the user clicks in the "Add Node" button. [2]

![image](https://user-images.githubusercontent.com/7024585/159025105-f3c228b5-6583-451a-bf07-24893cf763b5.png)

**Comment by zimaah** [comment]
With data.

![image](https://user-images.githubusercontent.com/7024585/159026004-cff51f00-de9a-4147-8536-9c465d2a5778.png)

**Comment by crsfalzon** [comment]
The scope of this ticket is limited to CL and Cosmos only. Substrate will be tackled individually before the release of the P1 metrics

**Comment by crsfalzon** [comment]
Post review @zimaah
