### ISSUE TITLE
Installation Wizard - Alerts Setup

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#50]
As a node operator, I want to be able to customize what metrics I want to be alerted on and their respective threshold.

**Requirements**
- A page must be displayed at _/installation/alerts_ 
- It must have an **svc-data-table** to configure the threshold values for each alert
- It must have an **svc-data-table** to configure the severity for each alert
- A "info" button must be provided, so the node operator can click and get to know more information about what he's configuring at the moment. This in-depth info must be displayed in a modal.
- The page must have a "back" button, so the node operator can navigate to the previous step (Repositories setup)
- The page must have a "next" button, so the node operator can navigate to the next step (Config Review)
- When the "next" button is clicked, the current configuration is saved in the local storage (browser cache)

**Comment by zimaah** [comment]
Notice: in the prototypes some icons are missing in the footer, stick with what we have currently for PANIC UI.


![image](https://user-images.githubusercontent.com/7024585/159744455-1fcb74e4-eaf8-4932-833d-0f9345e62e89.png)

**Comment by zimaah** [comment]
![image](https://user-images.githubusercontent.com/7024585/159744664-5b7922dc-7d4f-4cfe-83f2-a4eaa85782e4.png)

**Comment by zimaah** [comment]
![image](https://user-images.githubusercontent.com/7024585/159744754-9e27b05c-7bbf-496e-8695-8edc2dc90dd1.png)

**Comment by zimaah** [comment]
![image](https://user-images.githubusercontent.com/7024585/159744854-6249d034-7e35-474b-9b92-22ab1df83b00.png)

**Comment by crsfalzon** [comment]
Duplicate
