### ISSUE TITLE
Installation Wizard - Feedback

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#53]
As a node operator, I would like to see a page that tells me that the process was completed with success. The page must also give me the option to restart the installer - to add more sub-chains - or go to the home page.

Requirements

- A page must be displayed at _/installation/feedback_.
- A brief message/picture must be displayed giving the user a positive feedback
- Two buttons must be displayed:
   - "restart process" button, so the node operator can add more sub-chains
   - "go to home page" button, so the node operator can navigate back and check the config that he just did

**Comment by zimaah** [comment]
Notice: in the prototypes some icons are missing in the footer, stick with what we have currently for PANIC UI.



![image](https://user-images.githubusercontent.com/7024585/159750915-f6bedc3b-ebb8-46d1-bf31-b1ff2d9c0254.png)

**Comment by zimaah** [comment]
If the node operator finishes the installer for the second time in a row, then the node operator will see a **svc-data-table** showing the previously configured sub-chains.

![image](https://user-images.githubusercontent.com/7024585/159910490-7a51d38e-054b-431c-a032-965b28210191.png)

**Comment by crsfalzon** [comment]
Omit 'Configured' checkbox

**Comment by crsfalzon** [comment]
Duplicate
