### ISSUE TITLE
CRUD - Sub-Chains Home Page

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#57]
As a node operator, I would like to see a page that shows all sub-chains that I have configured and a filter, so I can filter the sub-chains by base-chain.

**Requirements**

- An menu item with the label "Sub-Chains" must be added to the _Settings_ menu
- When the node operator clicks in the option, a page located at _/sub-chains_ is shown
- The page must have an **svc-data-table**, to allow the node operator to perform CRUD operations over the sub-chains
- The page must have a filter, to allow the node operator to filter the data table by base-chain
- The page must have an "Add Sub-Chain" button, to allow the node operator to add new sub-chains
- When the node operator clicks in the "Edit" button (to edit a specific sub-chain), the app is redirected to _/sub-chains/SUB_CHAIN_ID/menu_
- When the node operator clicks in the "Delete" button, a dialog is shown asking the node operator if the sub-chain (along with all its configuration*) should be removed.
   - *_All the configuration under that deleted sub-chain must be removed, but the channels remain intact since they can be used across different sub-chains_

**Comment by Cherrett** [comment]
For now, we must make sure to not allow users to edit sub-chain names. This will be changed once #177 is implemented.
