### ISSUE TITLE
CRUD Channels

### ISSUE THREAD

**Issue by zimaah** [SimplyVC/panic#63]
As a node operator, I would like to see a page showing the channels that I have added to the platform and perform CRUD operations over it.

**Requirements**

- A "home page" for Channels must be created and be displayed at _/channels_
- The page must have a button with the label "Add Channel", allowing the node operator to add more channels. The form for the new channel must be displayed at _/channels/create_.
- The page must have an **svc-data-table** showing the channels that have been added so far. A channel type filter must be provided, allowing the node operator to filter the data table. A special column will be rendered, allowing the node operator to perform edit/delete actions over the channels.
      - When the node operator clicks in the "edit" button, a modal is shown with a form populated with the channel data.
      - When the node operator clicks in the "delete" button, a dialog is shown asking the node operator to confirm the action.
- The page must have a secondary **svc-data-table** along with a channel filter. The data table will be populated with sub-chains and the filter with channels. The idea is to provide an easy way to associate one specific channel to multiple sub-chains. In the data table, we will have a _checkbox_ telling if the channel is active or not for that specific sub-chain.
-  The page must have a "go back" button in the header, placed at the far left. It leads the node operator to the home page.
- The page must have a "help" button so the node operator can click and get to know more information about what he's configuring at the moment. This in-depth info must be displayed in a modal.

**Comment by crsfalzon** [comment]
Duplicate
