### ISSUE TITLE
Investigation - Data Store Francesco

### ISSUE THREAD

**Issue by crsfalzon** [SimplyVC/panic#68]

**Comment by dillu24** [comment]
Before starting off the data store I suggest you look at the following:

1. RabbitMQ and Pika to see how components interact with each other
2. Look at what data is being sent by the CosmosNodeMonitor and the CosmosNetworkMonitor
3. Look at what data is being sent by the CosmosNodeDataTransfomer and the CosmosNetworkDataTransformer (Still needs to be designed)
4. See how other data stores operate within PANIC.
